pipeline:
  build:
    image: registry.haktec.de/jekyll:86e0546618060dc5c7d00ff66ce218022768d4a0
    environment:
      TARGET: production
    commands:
      - make build
    when:
      branch:
        include: "*"
        exclude: staging

  build_staging:
    image: registry.haktec.de/jekyll:86e0546618060dc5c7d00ff66ce218022768d4a0
    environment:
      TARGET: staging
    commands:
      - make build
    when:
      branch:
        - staging

  package:
    image: registry.haktec.de/docker:2bf92189803126ca18eb9dc75ae689ffc6319ffa
    environment:
      TARGET: production
    commands:
      - make image
      - make push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: quay.io/honestbee/drone-kubernetes:master
    deployment: de-haktec-blog-staging
    kubernetes_server: ${KUBERNETES_SERVER}
    # kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    repo: registry.haktec.de/blog
    container: blog
    tag: ${DRONE_COMMIT_SHA}
    namespace: default
    when:
      branch:
        - staging
    secrets:
      - KUBERNETES_SERVER
      # - KUBERNETES_CERT
      - KUBERNETES_TOKEN

  deploy:
    image: quay.io/honestbee/drone-kubernetes:master
    deployment: de-haktec-blog
    kubernetes_server: ${KUBERNETES_SERVER}
    # kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    repo: registry.haktec.de/blog
    container: blog
    tag: ${DRONE_COMMIT_SHA}
    namespace: default
    when:
      branch:
        - master
    secrets:
      - KUBERNETES_SERVER
      # - KUBERNETES_CERT
      - KUBERNETES_TOKEN
