kind: pipeline
type: kubernetes
name: release
trigger:
  branch:
  - master
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote --init

- name: resume
  image: registry.hkoerber.de/latex:latest
  commands:
  - cd contrib/resume
  - pdflatex -halt-on-error -output-format pdf -interaction errorstopmode -draftmode resume.tex
  - pdflatex -halt-on-error -output-format pdf -interaction errorstopmode -draftmode resume.tex
  - pdflatex -halt-on-error -output-format pdf -interaction errorstopmode resume.tex

- name: resume-html
  image: registry.hkoerber.de/pdf2htmlex:65507e872f79c29dfde25f83d3f0666617ee1c5f
  commands:
  - cd contrib/resume
  - >-
    pdf2htmlEX
    --fit-width 1024
    --embed cfijo
    --dest-dir html-out
    --embed-external-font 1
    resume.pdf
    index.html

- name: gather-assets
  image: alpine
  commands:
  - cp contrib/resume/resume.pdf static/assets/resume/Hannes_Koerber_Resume.pdf
  - cp -r contrib/resume/html-out static/assets/resume-html

- name: build
  image: registry.hkoerber.de/hugo:f216de6b127620641bcaf1d28fe16bf1ea2db884
  commands:
  - >-
    /app/bin/hugo
    --baseURL=https://blog.hkoerber.de/
    --cleanDestinationDir
    --minify
    --destination ./public/
  - chmod -R o+rX ./public/

- name: image
  image: registry.hkoerber.de/drone-kaniko:latest
  settings:
    dockerfile: Dockerfile.nginx
    registry: registry.hkoerber.de
    repo: blog
    tags:
    - ${DRONE_COMMIT_SHA}

- name: update k8s
  image: alpine/git
  commands:
  - git clone https://code.hkoerber.de/hkoerber/mycloud mycloud
  - cd mycloud/k8s/blog
  - "sed -i 's#image: registry.hkoerber.de/blog:.*$#image: registry.hkoerber.de/blog:${DRONE_COMMIT_SHA}#' 50-deployment.yaml"
  # Check if file actually changed, we're done if it did not. Most likely a
  # pipeline re-run
  - git diff --exit-code --quiet -- 50-deployment.yaml && exit 0 || true
  - git add 50-deployment.yaml
  - "git commit -m 'k8s: Update blog container image'"
  - git push origin master
